### ISSUE TITLE
Checklist for Bordeaux (Robocup Junior + Meetup CM Arkéa One Point)

### ISSUE THREAD

**Issue by Benvii** [mdl29/donkeycarLPH#266]
Based on Nante one : 

- [ ] Sono (Ville de Brest) avec micro cravate + cordon secteur
- [ ] A mallet (maillet)
- [ ] Lingettes désinfectantes
- [ ] 4 tapis anti-dérapant (de soudure)
- [ ] Poids
- [ ] Serre flex
- [ ] Gâteaux
- [ ] Boissons
- [ ] Grand Câble HDMI
- [ ] Enrouleur de cable (la grosse rallonge)
- [ ] Panneau LPH
- [ ] Tuyaux avec isolent
- [ ] Mètre
- [ ] Paire de cisseaux
- [ ] Tapis
- [ ] Pieds pour le panneau
- [ ] Tour IR
- [ ] Multi-prise
- [ ] Télévision + support
- [ ] Caisses (voitures, batteries de moteur, batteries externes, RPI, Manettes ps4)
- [ ] Pinces coupantes
- [ ] Télécommande pour la télé
- [ ] 1 PC mdl pour le register
- [ ] divers (3) pc portable avec étiquettes
- [ ] plots de chantier 
- [ ] diable et plateau
- [ ] couvertures
- [ ] t-shirt DNSimple

Stéphane Blanc : 

- [ ] Plaques lourdes en alu (pour faire du poids autours de la piste

Benjamin :
- [ ] tours de coup
- [ ] goblets plastique
